# Generated by Django 3.2.16 on 2023-01-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('share_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='share_ID')),
                ('share_tag', models.CharField(max_length=255, verbose_name='share_Tag')),
                ('share_name', models.CharField(max_length=255, verbose_name='share_name')),
                ('share_sector', models.CharField(max_length=255, verbose_name='share_sector')),
                ('share_value1', models.FloatField(verbose_name='value1')),
                ('share_value2', models.FloatField(verbose_name='value2')),
                ('share_historical', models.CharField(max_length=50, verbose_name='historical')),
            ],
        ),
    ]
