# Generated by Django 3.2.16 on 2023-02-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('share_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='share_ID')),
                ('share_tag', models.CharField(max_length=255, verbose_name='share_tag')),
                ('share_name', models.CharField(max_length=255, verbose_name='share_name')),
                ('share_sector', models.CharField(max_length=255, verbose_name='share_sector')),
                ('share_volatility', models.FloatField(default=0.0, verbose_name='volatility')),
                ('share_peg_ratio', models.FloatField(default=0.0, verbose_name='peg_ratio')),
                ('share_beta_factor', models.FloatField(default=0.0, verbose_name='beta_factor')),
                ('share_historical', models.CharField(max_length=255, verbose_name='historical')),
                ('share_compound', models.FloatField(default=0.0, verbose_name='compound')),
                ('share_market_cap', models.FloatField(default=0.0, verbose_name='market_cap')),
                ('share_volume', models.FloatField(default=0.0, verbose_name='volume')),
                ('last_share_price', models.FloatField(default=0.0, verbose_name='last_close_price')),
                ('risk_level', models.FloatField(default=0, verbose_name='risk_level')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.IntegerField(default=0, verbose_name='risk_level')),
            ],
        ),
    ]
