# Generated by Django 3.2.16 on 2023-01-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='share_value1',
        ),
        migrations.RemoveField(
            model_name='share',
            name='share_value2',
        ),
        migrations.AddField(
            model_name='share',
            name='share_beta_factor',
            field=models.FloatField(default=0.0, verbose_name='beta_factor'),
        ),
        migrations.AddField(
            model_name='share',
            name='share_compound',
            field=models.FloatField(default=0.0, verbose_name='compound'),
        ),
        migrations.AddField(
            model_name='share',
            name='share_peg_ratio',
            field=models.FloatField(default=0.0, verbose_name='peg_ratio'),
        ),
        migrations.AddField(
            model_name='share',
            name='share_volatility',
            field=models.FloatField(default=0.0, verbose_name='volatility'),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_historical',
            field=models.CharField(max_length=255, verbose_name='historical'),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_tag',
            field=models.CharField(max_length=255, verbose_name='share_tag'),
        ),
    ]
