# Generated by Django 3.2.16 on 2023-01-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideo', '0002_auto_20230110_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='last_share_price',
            field=models.FloatField(default=0.0, verbose_name='last_close_price'),
        ),
        migrations.AddField(
            model_name='share',
            name='share_market_cap',
            field=models.BigIntegerField(default=0.0, verbose_name='market_cap'),
        ),
        migrations.AddField(
            model_name='share',
            name='share_volume',
            field=models.BigIntegerField(default=0.0, verbose_name='volume'),
        ),
    ]
