# Generated by Django 3.2.16 on 2023-01-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideo', '0003_auto_20230110_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='share_market_cap',
            field=models.FloatField(default=0.0, verbose_name='market_cap'),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_volume',
            field=models.FloatField(default=0.0, verbose_name='volume'),
        ),
    ]
