# Generated by Django 3.2.16 on 2023-01-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideo', '0004_auto_20230110_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='risk_level',
            field=models.IntegerField(default=0, verbose_name='risk_level'),
        ),
    ]
