# Generated by Django 3.2.16 on 2023-01-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideo', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='risk_level',
            field=models.IntegerField(default=0, verbose_name='risk_level'),
        ),
    ]
