# Generated by Django 3.2.16 on 2023-01-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fideo', '0007_alter_user_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='risk_level',
            field=models.FloatField(default=0, verbose_name='risk_level'),
        ),
    ]
